### Welcome message to check the database is set up
GET http://localhost:8080/api/admin/invoiceDetails/1

### Updates an existing person
PUT http://localhost:8080/api/users/Christoffer
Content-Type: application/json

{
  "userName": "Christoffer",
  "userPass": "test123",
  "userEmail": "chris@gmail.com",
  "userPhone": 10203040,
  "userBillingPrHour": 400
}

### List of all users
GET http://localhost:8080/api/developer/myProjects/admin
Content-Type: application/json

### System greets the admin in this case, if he's  logged in
GET http://localhost:8080/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

### Creates a new person
POST http://localhost:8080/api/developer/record
Content-Type: application/json

{
  "projectId": 1,
  "userName": "Christoffer",
  "hoursSpent": 30,
  "userStory": 3,
  "description": "hihi"
}





### Deletes an existing person
DELETE http://localhost:8080/api/developer/1
Content-Type: application/json

